### ISSUE TITLE
event-detection-pytorch: No install.sh + inputs unclear for extract_data.py

### ISSUE THREAD

**Issue by lashmore** [NewsEye/event-detection#7]
The README.md in event-detection-pytorch mentions a ./install.sh, but it was not included in the repo. It's unclear what this bash script contains and if it's necessary for using the event-detection-pytorch codebase. 

It's also unclear how json outputs from ace2005-preprocessing (which looks like it just uses StanfordCoreNLP's parser for ACE 2005 dataset) relate to the .txt inputs expected by event-detection-pytorch/extract_data.py.

**Comment by EmanuelaBoros** [comment]
Hello @lashmore, I'm looking into it and I'll update ASAP.

**Comment by EmanuelaBoros** [comment]
Hello, I updated the Readme with more details about the format. Unfortunately, I do not have anymore the script that changes the json files info the needed format. But maybe having more details about this format (Readme) could help. I added the details in the install.sh also.
